
import pandas as pd
from math import ceil


def shift_until_first_nonzero(series: pd.Series) -> pd.Series:
    """
    Remove leading zeros from a Series and reset index.

    If all values are zero, returns a Series of None with same length.

    Parameters
    ----------
    series : pd.Series (e.g. a column of a dataframe)

    Returns
    -------
    pd.Series
    """
    if series.eq(0).all():
        return pd.Series([None] * len(series))

    # Find first non-zero index
    first_valid_id = series.ne(0).idxmax()
    
    # Shift up
    shifted = series.loc[first_valid_id:].reset_index(drop=True)
    
    return shifted


def sort_centers_by_first_activity(df: pd.DataFrame, date_col: str, centers: list) -> pd.DataFrame:
    """
    Sort center columns based on their first non-zero occurrence.

    Centers with no activity are placed at the end.

    Parameters
    ----------
    df : pd.DataFrame
        It is output of generate_subject_counts function.
    date_col : str
    centers : list

    Returns
    -------
    pd.DataFrame
    """
    order = {date_col: -1} # Keep date column in the first place always

    for center in centers:
        if df[center].eq(0).all():
            order[center] = float('inf') # If all values are zero, assign a LARGE value
        else:
            order[center] = df[center].ne(0).idxmax()

    sorted_cols = sorted(order, key=order.get)
    return df.reindex(columns=sorted_cols)


def generate_subject_counts(time_unit: str, start_date,  end_date,
                            df: pd.DataFrame, center_col: str, date_col: str):
    """
    Compute subject counts per time unit and center.

    Supports:
    - Calendar time
    - Time since first inclusion (aligned per center)

    Returns
    -------
    counts_df : pd.DataFrame
    centers : list
    """

    # Create full time range
    freq_map = {"Day": "D", "Week": "W", "Month": "M"}
    freq = freq_map[time_unit]

    # Convert start/end dates to UTC
    start_date = pd.Timestamp(start_date, tz="UTC")

    # Include full end day
    end_date = (
        pd.Timestamp(end_date, tz="UTC")
        + pd.Timedelta(days=1)
        - pd.Timedelta(seconds=1)
    )

    # Filter rows by specified time period [start_date, end_date]
    filtered_df = df[
        (df[date_col] >= start_date) &
        (df[date_col] <= end_date)
    ]

    full_range = pd.period_range(
        start=start_date,
        end=end_date,
        freq=freq
    )

    # Aggregate counts: Count subjects per time unit
    counts_df = (
        filtered_df
        .groupby([
            filtered_df[date_col].dt.to_period(freq), 
            filtered_df[center_col]
        ])
        .size()
        .unstack(fill_value=0) # columns = centers
        .reindex(full_range, fill_value=0) # Include time ranges (days, weeks, month) with 0 subject included
    )
    
    # Add time column: Date (df.index) is inserted as a column called 'Date'
    date_col = 'Time'
    counts_df.insert(0, date_col, counts_df.index.astype(str))
    
    # Reset index from 1 to len(counts) for better visualisation
    counts_df.index = range(1, len(counts_df)+1)

    # Sort centers
    centers = filtered_df[center_col].dropna().unique().tolist()
    counts_df = sort_centers_by_first_activity(counts_df, date_col, centers)
    centers = [col for col in counts_df.columns if col!=date_col]
    
    return counts_df, centers


def opening_time_alignment(time_unit: str, counts_df: pd.DataFrame, centers: list, date_col='Time'):
    """
    Relative time alignment: 
    Drop leading zero elements to align inclusion timeline across centers based on the occurrence of first inclusion.
    """
    
    aligned = counts_df[centers].apply(shift_until_first_nonzero)

    # Rebuild into a proper DataFrame (columns may have different lengths)
    counts_df = pd.DataFrame({
        col: pd.Series(aligned[col].dropna().values)
        for col in centers
    })
    # Reset index from 1 to len(counts) for better visualisation
    counts_df.index = range(1, len(counts_df)+1)

    # Add "Time" since first inclusion
    counts_df.insert(0, 
                     date_col, 
                     [f"{time_unit} {i+1}" for i in range(len(counts_df))])
    
    return counts_df


def replace_0_by_none_after_closure_date(counts_df: pd.DataFrame, closure_dates: dict) -> pd.DataFrame:
    """
    For inactive centers (0 inclusion/completion), replace 0 by None after the closure date.

    Parameters
    ----------
    counts_df: pd.DataFrame
        counts_df generated by generate_subject_counts function.
    closure_dates: dict {str:str}
        {center: closure_date}
    
    Returns
    ----------
    counts_df
    """
    for center in closure_dates:
        closure_date = closure_dates[center]
        closure_index = counts_df[counts_df["Time"]==closure_date].index.values[0]
        counts_df.loc[closure_index:, center] = None
    return counts_df


def find_inactive_centers(counts_df: pd.DataFrame, centers: list) -> list:
    inactive_centers = []
    for center in centers:
        if counts_df.iloc[-1][center]==0:
            inactive_centers.append(center)
    return inactive_centers


def find_last_active_time(series: pd.Series) -> int:
    """
    In a given series, find the first non-zero element from bottom to top.
    If all elements are zero, returns 0.

    Parameters
    ----------
    series: pd.Series
        A column of counts_df generated by generate_subject_counts function.
    
    Returns
    ----------
    index: int64
    """
    if series.eq(0).all():
        return 0

    # Find first non-zero element's index from bottom to top
    rev = series.iloc[::-1]
    index = rev[rev.ne(0)].index[0]

    return index


def generate_stats(counts_df: pd.DataFrame, centers: list, time_unit: str, time_scale: str) -> pd.DataFrame:
    """
    Compute descriptive statistics per center.

    Returns a formatted DataFrame ready for display.
    """
    stats = pd.DataFrame(index=[f"{time_unit} periods", 
                                "Total subjects",
                                "Mean",
                                "Median",
                                "Std",
                                "Min",
                                "Max",
                                f"{time_unit} with 0 inclusion (%)"
                                ], 
                                columns=centers)
                
    for center in centers:
        series = counts_df[center].dropna()

        if series.empty:
            stats[center] = None
            continue
        
        n_periods = len(series)
        total = int(series.sum())

        stats.loc[f"{time_unit} periods", center] = n_periods
        stats.loc["Total subjects", center] = total
        stats.loc["Mean", center] = round(series.mean(), 2)
        stats.loc["Median", center] = series.median()
        stats.loc["Std", center] = round(series.std(), 2)
        stats.loc["Min", center] = int(series.min())
        stats.loc["Max", center] = int(series.max())

        zero_count = (series == 0).sum()
        zero_pct = round(zero_count / n_periods * 100)
        stats.loc[f"{time_unit} with 0 inclusion (%)", center] = f"{zero_count} ({zero_pct}%)"

    # Type uniformization for visualisation of output with st.write without waning
    stats = stats.astype(str)
    
    # Remove statistical indications when time_scale is "Calendar time" since they are misleading.
    if time_scale=="Calendar time":
        stats = stats.loc[[f"{time_unit} periods",
                         "Total subjects"]
                    ]
    return stats


def generate_metrics(counts_df: pd.DataFrame, center: str, closure_dates:dict):
    """
    Compute last value and relative change for a center.
    """
    if center in closure_dates:
        return "Closed", "—"
    
    series = counts_df[center].dropna()

    if len(series) == 0:
        # all values in counts_df[center] are None -> No subject inclusion -> No stat
        return "—", "—"
    
    if len(series) == 1:
        return str(int(series.iloc[-1])), "—"
    
    last = series.iloc[-1]
    prev = series.iloc[-2]

    if prev == 0:
        delta = "—"
    else:
        delta = f"{round((last - prev) / prev * 100)}%"

    return str(int(last)), delta


def compute_end_estimation(time_unit: str, min_date:str, end_date, counts_df: pd.DataFrame, df: pd.DataFrame,
                            center_col, date_col, centers: list, targets: dict) -> dict:
    """
    Estimate remaining time to reach target subjects per center.
    The estimation method is based on average recruitment rate. 
    In future, a second estimation based on median rate can be added.

    Parameters
    ----------
    time_unit: str
    end_date: datetime.date, output of st.date_input()
        End of time range, selected by user.
    min_date:
        Beginning of the study i.e. the first found in df
    counts_df: pd.DataFrame
        Counts of subjects in the time period selected by user, generated by generate_subject_counts function.
    df: pd.DataFrame
    centers: [str]
        Center names generated by generate_subject_counts function.
    targets: dict {str: int}
        {center: expected subject count}
    
    Returns
    ----------
    result: pd.DataFrame
    """
    # Count subjects and generate stats since the beginning of the study, regardless of start date selected by user
    counts_df_since_beginning, _ = generate_subject_counts(time_unit, min_date, end_date, df, center_col, date_col)
    counts_df_since_beginning = opening_time_alignment(time_unit, counts_df_since_beginning, centers)
    stats_since_beginning = generate_stats(counts_df_since_beginning, centers, time_unit, time_scale="Time since first")

    # Generate stats in the time period selected by user
    counts_df = opening_time_alignment(time_unit, counts_df, centers)
    stats = generate_stats(counts_df, centers, time_unit, time_scale="Time since first")

    # Generate outputs
    REMAIN = "Estimated remaining time"
    END = "Estimated end time"
    index = pd.Index(
        ["Target subjects", 
         "Recruited subjects (%)*",
         REMAIN,
         END
         ],
         name="Metrics"
    )
    result = pd.DataFrame(index=index, columns=centers)

    for center in centers:
        target = int(targets[center])
        recruited = int(stats_since_beginning.loc["Total subjects", center])
        mean_rate = float(stats.loc["Mean", center])
        # median_rate = float(stats.loc["Median", center])

        if target==0:
            result.loc[:, center] = "—"
            continue

        result.loc["Target subjects", center] = target
        result.loc["Recruited subjects (%)*", center] = f"{recruited} ({round(recruited/target*100)}%)"

        if recruited >= target:
            result.loc[REMAIN, center] = "0"
            result.loc[END, center] = "Completed"
            continue
        
        if mean_rate==0:
            result.loc[REMAIN, center] = "Not estimable"
            result.loc[END, center] = "Not estimable"
            continue
        else:
            # Estimated remaining time
            remaining = ceil((target - recruited) / mean_rate)
            result.loc[REMAIN, center] = f"{remaining} {time_unit}s"

            # Compute estimated end date
            offset_map = {
                "Day": pd.DateOffset(days=remaining),
                "Week": pd.DateOffset(weeks=remaining),
                "Month": pd.DateOffset(months=remaining),
            }
            estimated_end_date = (
                pd.to_datetime(end_date)
                + offset_map[time_unit]
            ).strftime("%Y-%m-%d")
            result.loc[END, center] = estimated_end_date

    result = result.astype(str)

    return result        

        
    


